### ISSUE TITLE
Upload to pip index

### ISSUE THREAD

**Issue by gjulianm** [fmagin/networkx-stubs#1]
Hello! 

I just found this project and I find it pretty useful, I'm adding support for the Multi[Di]Graph classes and will make a PR when I have it working. I only have one question, which is whether you plan on uploading this to the Pypi index at some point. I do not need it now but it would be useful to make installation easier, especially in CI environments.

**Comment by fmagin** [comment]
Glad to know that you find it useful and looking forward to any contributions!

If your CI environment has access to Github, you can do something like
```sh
pip install https://github.com/fmagin/networkx-stubs/archive/master.zip
```
or [various other notations](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch)  depending on your exact need. I checkout from specific commit IDs in my CI setups, so pip caches this commit and the CI shares that cache between runs. This also works for tags, so I could just do pseudo releases and have a `latest-stable` tag or something.

Concerning the actual issue of publishing this to PyPI:
I am not sure at what point I'd feel comfortable with this. For now this still really early WIP, and has no guarantees to actually still match any specific version of networkx. I think my preferred approach would be to get this into a state where the networkx project itself would be willing to add it to their Github namespace. Or maybe even accepts moving the annotations into the actual codebase, given that -stub packages are for third party annotations.

I guess if it turns out that the networkx project doesn't want annotations in their code and doesn't want to maintain a stub package, I at least want some other maintainers for this project before publishing it anywhere.

**Comment by gjulianm** [comment]
Ok, I understand. I will add for now the Github URL and will make the PR when I have more things added. 

Thanks!

**Comment by gjulianm** [comment]
Apparently looks like someone else is working on this too: networkx/networkx#4014 networkx/networkx#3988
