### ISSUE TITLE
Merge tighter annotations?

### ISSUE THREAD

**Issue by NeilGirdhar** [fmagin/networkx-stubs#2]
Awesome project!  Would you consider merging in [my annotations](https://github.com/networkx/networkx/pull/4014) that are quite a bit tighter than the ones currently provided?

**Comment by fmagin** [comment]
What do you mean by "tighter" ? I skimmed your annotations earlier and they seemed mostly similar to mine, but it has been a while since I actually read my annotation code, so I might be missing things.
In general I am happy to merge any improvements, though I don't have much time to do it myself currently. It should be enough to use `stubgen` on your annotated code though to generate new stubs and then combine my existing stubs and the new generated ones in some sensible way.

**Comment by NeilGirdhar** [comment]
There were some similar things.  We both made generic types, but my annotations are tighter, e.g., in `Graph`
Yours:
```python
    def nbunch_iter(self, nbunch: Optional[Any] = ...): ...
    def size(self, weight: Optional[Any] = ...): ...
    def update(self, edges: Optional[Any] = ..., nodes: Optional[Any] = ...) -> None: ...
```
Mine:
```python
    def nbunch_iter(self,
                    nbunch: Union[None, Node, Iterable[Node]] = None) -> (
                        Iterator[Node]):

    @overload
    def size(self, weight: None = None) -> int:
        ...
    @overload
    def size(self, weight: str) -> Real:
        ...
    def size(self, weight: Optional[str] = None) -> Real:  # type: ignore

    def update(self,
               edges: Optional[Union[Graph[Node], Iterable[EdgePlus]]] = None,
               nodes: Optional[Iterable[Node]] = None) -> None:
```
I've never used `stubgen`.  I did change the code in a few places to resolve a Liskov violation and some very poor design choices.

**Comment by fmagin** [comment]
https://mypy.readthedocs.io/en/stable/stubgen.html is what I am referring to (either as an info for you or anyone else reading this)

I think all those `Optional[Any]` are the result of `stubgen` seeing a keyword argument with a default value of `None` and automatically inferring that it is an `Optional` of something. I am fairly sure that I never needed those methods myself, and for some the annotations are quite obvious so I'd expect if I'd done it myself I would have added proper annotations.

Networkx does have some weird design choices that don't go well together with typing, but I am not sure how open they are to changing that code. I still haven't managed to annotate it so PyCharm properly understands that iterating over a graph, or `graph.nodes` or `graph.nodes()` all will result in the Node TypeVar.

In general I am not sure yet which approach we should pursue: A stub package like this repo, or adding annotations to the actual code like you did. If the devs are open to the latter, I would prefer this a lot, and in the recent discussion it seemed like it. So before I start changing the code of this repo I'd like to wait what the long term plan will be, because I am short on time currently.
If you want to try out stubgen and extend the stub package I welcome any PRs.

**Comment by NeilGirdhar** [comment]
The thing is that `Optional[Any]`, which is the same as `Any` is as good as having no type annotation for that argument.

> but I am not sure how open they are to changing that code.

Yeah :(

> I still haven't managed to annotate it so PyCharm properly understands that iterating over a graph

Have you tried inheriting from `Collection[Node]` like I did?

> So before I start changing the code of this repo I'd like to wait what the long term plan will be, because I am short on time currently.

Same here.  Good thinking.

**Comment by fmagin** [comment]
> The thing is that `Optional[Any]`, which is the same as `Any` is as good as having no type annotation for that argument.

yep, that's basically why I was confused about the "tighter" description. I didn't really consider those methods annotated at all.

> Have you tried inheriting from `Collection[Node]` like I did?

I am not sure, but I'll test this when I get around to it. Thanks for the tip!

**Comment by charmoniumQ** [comment]
I've decided to take this up.

**Comment by songololo** [comment]
Just an FYI that there is recent work going on in NetworkX re: types. NetworkX is still sitting on the fence in terms of merging the work but just mentioning this in case that ongoing work can be dovetailed with this work?

**Comment by fmagin** [comment]
@songololo what kind of recent works? I guess you mean the discussions and progress in the last few weeks in https://github.com/networkx/networkx/pull/4014 ? I wasn't aware of that (I thought I was subscribed to it, but I guess I wasn't). There are way too many issues and PRs with discussions...

@charmoniumQ I greatly appreciate any effort into better type annotations, but at this point this stubs repo is probably also somewhat outdated. Inline Type Annotations in networkx itself are definitely the way to go. I'm tempted to just merge your PR without checking it much, but I don't really have any motivation to actually maintain the `networkx-stubs` package currently, because it's just way more effort than actual inline annotations.

**Comment by songololo** [comment]
@fmagin yes, that's the one, quite a bit of activity the last week or so, on again and off again...

**Comment by charmoniumQ** [comment]
I agree inline stubs are better in the long run, but I would like types today.

It can also serve as a "prototype" of type annotations waiting to be merged inline.

**Comment by fmagin** [comment]
@charmoniumQ fair enough, just merged your PRs. Do you also need a PyPI release, or are you installing this from the git repo directly anyway?

**Comment by charmoniumQ** [comment]
I'll install directly from git repo.
